---
#################################################
# Red Hat Advanced Deployment Homework Playbook
# Author: B.F. Taljaard
# Date: 12 Nov 2018
#################################################

# Run init playbook
- name: Execute the init playbook
  import_playbook: /root/rh_adv_deployment_homework/playbooks/init.yaml

# Run install playbook
#- name: Execute the install playbook
#  import_playbook: /root/rh_adv_deployment_homework/playbooks/install.yaml

# Run verify playbook
- name: Execute the verify playbook
  import_playbook: /root/rh_adv_deployment_homework/playbooks/verify.yaml

# Run nfs playbook
- name: Execute the nfs playbook
  import_playbook: /root/rh_adv_deployment_homework/playbooks/nfs.yaml

# Run smoke test
- name: Deploy smoke test application to verify persistence is working
  hosts: localhost
  tasks:
    - name: Run smoke test script
      script: /root/rh_adv_deployment_homework/scripts/smoke_test.sh

