---
- name: Get GUID for environment
  hosts: all
  tasks:
     - shell: hostname | cut -d"." -f2
       register: GUID
       ignore_errors: True

- name: Export GUID on all machines
  hosts: all
  tasks: 
    - name: Export GUID env variable
      shell: export GUID={{ GUID }}

- name: Add GUID export to bashrc
  hosts: all
  tasks:
    - name: Add GUID export to bashrc
      lineinfile:
        path: $HOME/.bashrc
        line: export GUID={{ GUID }}


- name: Ensure docker is installed
  hosts: nodes
  tasks:
    - name: Docker is installed
      yum:
        name:
          - docker-1.13.1
        state: present

- name: Verify NFS Shared Volumes
  hosts: nfs
  tasks:
    - name: Check NFS share exists
      shell: exportfs|grep /srv/nfs
