---
#################################################
# Red Hat Advanced Deployment Homework Playbook
# Author: B.F. Taljaard
# Date: 12 Nov 2018
#################################################

# Get GUID for environment
- name: Get GUID for environment
  hosts: all
  tasks:
     - shell: hostname | cut -d"." -f2
       register: GUID
       ignore_errors: True

# Set GUID on all machines
- name: Add GUID export to bashrc
  hosts: all
  tasks:
    - name: Add GUID export to bashrc
      lineinfile:
        path: $HOME/.bashrc
        line: export GUID={{ GUID['stdout'] }}

# Check Docker
- name: Ensure docker is installed
  hosts: nodes
  tasks:
    - name: Docker is installed
      yum:
        name:
          - docker-1.13.1
        state: present

# Check NFS
- name: Verify NFS Shared Volumes
  hosts: nfs
  tasks:
    - name: Check NFS share exists
      shell: exportfs|grep /srv/nfs

# Install openshift-ansible on bastion
- name: Install openshift packages
  hosts: localhost
  tasks:
    - name: openshift packages are present
      yum:
        name:
          - openshift-ansible
          - atomic-openshift-clients
        state: present

# Rename GUID in inventory file
- name: Generate Inventory Hosts File
  hosts: localhost
  tasks:
    - name: Generate Inventory script
      replace:
        path: /root/rh_adv_deployment_homework/ocp_inventory
        regexp: 'GUID'
        replace: "{{ GUID['stdout'] }}"

# Replace ansible hosts file
- name: Copy ansible hosts file into place, backing up the original if it differs from the copied version
  hosts: localhost
  copy:
    src: /root/rh_adv_deployment_homework/ocp_inventory
    dest: /etc/ansible/hosts
    owner: root
    group: root
    mode: 0644
    backup: yes


# Run pre-requisites playbook
- name: Execute the openshift-ansible prerequisites
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml



