---
#################################################
# Red Hat Advanced Deployment Homework Playbook
# Author: B.F. Taljaard
# Date: 12 Nov 2018
#################################################

# Run pre-requisites playbook
- name: Execute the openshift-ansible prerequisites playbook
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

# Run the deployment playbook
- name: Execute the openshift cluster deployment playbook
  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml