---
#################################################
# Red Hat Advanced Deployment Homework Playbook
# Author: B.F. Taljaard
# Date: 12 Nov 2018
#################################################

# Configure networking to be similar to multi-tenancy
- name: Execute network migrate script
  hosts: localhost
  tasks:
    - name: Execute network-policy migrate script
      script: /root/rh_adv_deployment_homework/scripts/migrate-network-policy.sh