---
#################################################
# Red Hat Advanced Deployment Homework Playbook
# Author: B.F. Taljaard
# Date: 12 Nov 2018
#################################################

# Run smoke test
- name: Deploy smoke test application to verify persistence is working
  hosts: localhost
  tasks:
    - name: Run smoke test script
      script: /root/rh_adv_deployment_homework/scripts/smoke_test.sh
